/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F446RE.h"

#include "STM32GPIO_DRIVER.h"

int main(void)
{
    GPIO_Handle_t GpioLed;

    // Configure PA5 as output (on-board LED on NUCLEO-F446RE)
    GpioLed.pGPIOx = GPIOA;
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_PUSHPULL;
    GpioLed.GPIO_PinConfig.GPIO_PinPUPDControl= GPIO_PUPDR_NO_PULL_UP;

    GPIO_PeriClockControl(GPIOA, ENABLE);
    GPIO_Init(&GpioLed);

    while(1)
    {
    	GPIO_TOGGLEOUTPUTPIN (GPIOA, GPIO_PIN_NO_5 );
        for(uint32_t i = 0; i < 500000; i++); // Simple delay
    }

    return 0;
}


