/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdio.h>
#include "STM32F446RE.h"
#include "STM32_GPIO_DRIVER.h"
#include "STM32_USART_DRIVER.h"

#include <string.h>

USART_Handle_t USART2Handle;

// Function to initialize USART2 Pins (PA2, PA3)
void USART2_GPIOInit(void)
{
    GPIO_Handle_t USARTPins;
    USARTPins.pGPIOx = GPIOA;
    USARTPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    USARTPins.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
    USARTPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    USARTPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    USARTPins.GPIO_PinConfig.GPIO_PinAltFunMode = 7;

    GPIO_PeriClockControl(GPIOA, ENABLE);

    USARTPins.GPIO_PinConfig.GPIO_PinNumber =  GPIO_PIN_2; // TX
    GPIO_Init(&USARTPins);

    USARTPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_3; // RX
    GPIO_Init(&USARTPins);
}


void Button_GPIOInit(void)
{
    GPIO_Handle_t UserButton;
    UserButton.pGPIOx = GPIOC;
    UserButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
    UserButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
    UserButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    UserButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOC, ENABLE);
    GPIO_Init(&UserButton);
}

void USART2_Init(void)
{
	USART2_CLK_EN();
    USART2Handle.pUSARTx = USART2;
    USART2Handle.USART_Config.USART_Baud = USART_STD_BAUD_115200;
    USART2Handle.USART_Config.USART_HWFlowControl =USART_HW_FLOW_CTRL_NONE;
    USART2Handle.USART_Config.USART_Mode = USART_MODE_TXRX;
    USART2Handle.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
    USART2Handle.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
    USART2Handle.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;

    USART_Init(&USART2Handle);
}

int main(void)
{

    char msg[] = "BUTTON PRESSED\r\n";

    USART2_GPIOInit();
    Button_GPIOInit(); // Initialize the button hardware
    USART2_Init();

    USART_PeripheralControl(USART2, ENABLE);

    while (1)
    {

        if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_13) == 0)
        {
            // Send message ONLY when pressed
            USART_SendData(&USART2Handle, (uint8_t*)msg, strlen(msg));


            for (uint32_t i = 0; i < 500000; i++);
        }
    }

    return 0;
}

