/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F446RE.h"
#include "STM32_GPIO.h"
#include "STM32_I2C.h"
#include "STM32_UART.h"

#include <stdio.h>

/* LM75 I2C address */
#define LM75_ADDR       0x48
#define TEMP_REG        0x00

USART_Handle_t usart2;
I2C_Handle_t i2c1;

char buffer[100];

/************************************************************
 * Simple delay
 ************************************************************/
void delay(void)
{
    for(volatile uint32_t i = 0; i < 300000; i++);
}

/************************************************************
 * GPIO Init
 ************************************************************/
void GPIO_Init_All(void)
{
    GPIO_Handle_t gpio;

    /******** USART2 PA2 TX ********/
    gpio.pGPIOx = GPIOA;
    gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;
    gpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    gpio.GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_PUSHPULL;
    gpio.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    gpio.GPIO_PinConfig.GPIO_PinPUPDControl = GPIO_PUPDR_NO_PULL_UP;
    gpio.GPIO_PinConfig.GPIO_PinAltFuncmode = 7;
    GPIO_Init(&gpio);

    /******** USART2 PA3 RX ********/
    gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
    GPIO_Init(&gpio);

    /******** I2C1 PB8 SCL ********/
    gpio.pGPIOx = GPIOB;
    gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
    gpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    gpio.GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_OPENDRAIN;
    gpio.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    gpio.GPIO_PinConfig.GPIO_PinPUPDControl = GPIO_PUPDR_PULL_UP;
    gpio.GPIO_PinConfig.GPIO_PinAltFuncmode = 4;
    GPIO_Init(&gpio);

    /******** I2C1 PB9 SDA ********/
    gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
    GPIO_Init(&gpio);
}

/************************************************************
 * I2C Init
 ************************************************************/
void I2C1_Init(void)
{
    i2c1.pI2Cx = I2C1;
    i2c1.I2C_Config.I2C_ACKControl = I2C_ACK_ENABLE;
    i2c1.I2C_Config.I2C_DeviceAddress = 0x61;
    i2c1.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;
    i2c1.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;

    I2C_Init(&i2c1);
}

/************************************************************
 * USART Init
 ************************************************************/
void USART2_Init(void)
{
    usart2.pUSARTx = USART2;

    usart2.USART_Config.USART_Baud = USART_STD_BAUD_115200;
    usart2.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
    usart2.USART_Config.USART_Mode = USART_MODE_TXRX;
    usart2.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
    usart2.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
    usart2.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;

    USART_Init(&usart2);
}

/************************************************************
 * MAIN
 ************************************************************/
int main(void)
{
    GPIO_Init_All();
    I2C1_Init();
    USART2_Init();

    uint8_t rx[2];
    int16_t raw;
    float temp;

    while(1)
    {
        /* Set LM75 register pointer */
        I2C_MasterSendData(&i2c1, (uint8_t*)&(uint8_t){TEMP_REG}, 1, LM75_ADDR, 0);

        /* Read 2 bytes */
        I2C_MasterReceiveData(&i2c1, rx, 2, LM75_ADDR, 0);

        raw = (rx[0] << 8) | rx[1];
        raw >>= 7;

        temp = raw * 0.5;

        sprintf(buffer, "Temperature = %.2f C\r\n", temp);

        USART_SendString(&usart2, buffer);

        delay();
    }
}
