/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F446RE.h"
#include "STM32_GPIO_DRIVER.h"
#include "STM32_SPI_DRIVER.h"

void SPI1_GPIOInits(void);
void SPI1_Inits(void);

int main(void)
{
    uint8_t tx_data[] =
    {
        0xAA,
        0x55,
        0xFF,
        0x00,
        0x12,
        0x34,
        0x56,
        0x78
    };

    SPI1_GPIOInits();
    SPI1_Inits();

    // Required when Software Slave Management (SSM) is enabled
    SPI_SSIConfig(SPI1, ENABLE);

    // Enable SPI peripheral
    SPI_PeripheralControl(SPI1, ENABLE);

    while(1)
    {
        SPI_SendData(SPI1, tx_data, sizeof(tx_data));

        // Small delay
        for(uint32_t i = 0; i < 500000; i++);
    }
}

void SPI1_GPIOInits(void)
{
    GPIO_Handle_t SPIPins;

    SPIPins.pGPIOx = GPIOA;
    SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;      // AF5 = SPI1
    SPIPins.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
    SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    // SCK -> PA5
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
    GPIO_Init(&SPIPins);

    // MISO -> PA6 (optional if only transmitting)
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_6;
    GPIO_Init(&SPIPins);

    // MOSI -> PA7
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
    GPIO_Init(&SPIPins);

    // NSS -> PA4
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_4;
    GPIO_Init(&SPIPins);
}

void SPI1_Inits(void)
{
    SPI_Handle_t SPIHandle;

    SPIHandle.pSPIx = SPI1;

    SPIHandle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    SPIHandle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    SPIHandle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;
    SPIHandle.SPIConfig.SPI_DFF= SPI_DFF_8BITS;
    SPIHandle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    SPIHandle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    SPIHandle.SPIConfig.SPI_SSM= SPI_SSM_EN;

    SPI_Init(&SPIHandle);
}
